export type Country = { code: string; name: string; flag: string };

function toFlag(code: string): string {
  return [...code.toUpperCase()]
    .map((c) => String.fromCodePoint(c.charCodeAt(0) + 127397))
    .join("");
}

export const COUNTRIES: Country[] = [
  { code: "FR", name: "France", flag: toFlag("FR") },
  { code: "BE", name: "Belgique", flag: toFlag("BE") },
  { code: "CH", name: "Suisse", flag: toFlag("CH") },
  { code: "LU", name: "Luxembourg", flag: toFlag("LU") },
  { code: "CA", name: "Canada", flag: toFlag("CA") },
  { code: "MC", name: "Monaco", flag: toFlag("MC") },
  { code: "DZ", name: "Algérie", flag: toFlag("DZ") },
  { code: "MA", name: "Maroc", flag: toFlag("MA") },
  { code: "TN", name: "Tunisie", flag: toFlag("TN") },
  { code: "SN", name: "Sénégal", flag: toFlag("SN") },
  { code: "CI", name: "Côte d'Ivoire", flag: toFlag("CI") },
  { code: "CM", name: "Cameroun", flag: toFlag("CM") },
  { code: "US", name: "États-Unis", flag: toFlag("US") },
  { code: "GB", name: "Royaume-Uni", flag: toFlag("GB") },
  { code: "DE", name: "Allemagne", flag: toFlag("DE") },
  { code: "ES", name: "Espagne", flag: toFlag("ES") },
  { code: "IT", name: "Italie", flag: toFlag("IT") },
  { code: "PT", name: "Portugal", flag: toFlag("PT") },
  { code: "NL", name: "Pays-Bas", flag: toFlag("NL") },
  { code: "SE", name: "Suède", flag: toFlag("SE") },
  { code: "NO", name: "Norvège", flag: toFlag("NO") },
  { code: "DK", name: "Danemark", flag: toFlag("DK") },
  { code: "FI", name: "Finlande", flag: toFlag("FI") },
  { code: "PL", name: "Pologne", flag: toFlag("PL") },
  { code: "AT", name: "Autriche", flag: toFlag("AT") },
  { code: "CZ", name: "Tchéquie", flag: toFlag("CZ") },
  { code: "HU", name: "Hongrie", flag: toFlag("HU") },
  { code: "RO", name: "Roumanie", flag: toFlag("RO") },
  { code: "GR", name: "Grèce", flag: toFlag("GR") },
  { code: "TR", name: "Turquie", flag: toFlag("TR") },
  { code: "RU", name: "Russie", flag: toFlag("RU") },
  { code: "UA", name: "Ukraine", flag: toFlag("UA") },
  { code: "JP", name: "Japon", flag: toFlag("JP") },
  { code: "CN", name: "Chine", flag: toFlag("CN") },
  { code: "KR", name: "Corée du Sud", flag: toFlag("KR") },
  { code: "IN", name: "Inde", flag: toFlag("IN") },
  { code: "AU", name: "Australie", flag: toFlag("AU") },
  { code: "NZ", name: "Nouvelle-Zélande", flag: toFlag("NZ") },
  { code: "BR", name: "Brésil", flag: toFlag("BR") },
  { code: "MX", name: "Mexique", flag: toFlag("MX") },
  { code: "AR", name: "Argentine", flag: toFlag("AR") },
  { code: "CL", name: "Chili", flag: toFlag("CL") },
  { code: "CO", name: "Colombie", flag: toFlag("CO") },
  { code: "ZA", name: "Afrique du Sud", flag: toFlag("ZA") },
  { code: "EG", name: "Égypte", flag: toFlag("EG") },
  { code: "NG", name: "Nigéria", flag: toFlag("NG") },
  { code: "AE", name: "Émirats arabes unis", flag: toFlag("AE") },
  { code: "SA", name: "Arabie saoudite", flag: toFlag("SA") },
  { code: "IL", name: "Israël", flag: toFlag("IL") },
  { code: "SG", name: "Singapour", flag: toFlag("SG") },
  { code: "TH", name: "Thaïlande", flag: toFlag("TH") },
  { code: "VN", name: "Viêt Nam", flag: toFlag("VN") },
  { code: "ID", name: "Indonésie", flag: toFlag("ID") },
  { code: "PH", name: "Philippines", flag: toFlag("PH") },
];
